name: reown_flutter
description: "The communications protocol for web3"
version: 1.0.0
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

# dependencies:
#   flutter:
#     sdk: flutter

# dev_dependencies:
#   build_runner: ^2.4.7
#   dependency_validator: ^3.2.2
#   flutter_lints: ^2.0.0
#   flutter_test:
#     sdk: flutter