name: reown_yttrium
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 0.0.2
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_yttrium
documentation: https://docs.reown.com/walletkit/flutter/early-access/chain-abstraction

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  eth_sig_util_plus: ^0.0.10
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.reown.reown_yttrium
        pluginClass: ReownYttriumPlugin
      ios:
        pluginClass: ReownYttriumPlugin
