name: reown_core
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.3.8
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_core

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  bs58: ^1.0.2
  connectivity_plus: '>=6.1.3 <8.0.0'
  convert: ^3.1.2
  cryptography: ^2.7.0
  ed25519_edwards: ^0.3.1
  event: ^3.1.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  msgpack_dart: ^1.0.1
  package_info_plus: '>=8.1.2 <10.0.0'
  pointycastle: '>=3.9.1 <5.0.0'
  reown_yttrium:
    path: ../reown_yttrium/
  shared_preferences: ^2.3.4
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
  x25519: ^0.1.1

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  mockito: ^5.4.4

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
