name: reown_core
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.0.5
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_core

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bs58: ^1.0.2
  connectivity_plus: ^6.1.1
  convert: ^3.1.2
  cryptography: ^2.7.0
  ed25519_edwards: ^0.3.1
  event: ^3.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  package_info_plus: ^8.1.2
  pointycastle: ^3.9.1
  shared_preferences: ^2.3.3
  stack_trace: ^1.11.1
  stream_channel: ^2.1.2
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
  x25519: ^0.1.1

dependency_overrides:
  win32: ^5.9.0

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  dependency_validator: ^4.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mockito: ^5.4.4

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
