name: reown_walletkit
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.0.3
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_walletkit
documentation: https://docs.reown.com/walletkit/flutter/installation

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  event: ^3.1.0
  flutter:
    sdk: flutter
  # reown_core: ^1.0.4
  reown_core:
    path: ../reown_core/
  # reown_sign: ^1.0.4
  reown_sign:
    path: ../reown_sign/

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  dependency_validator: ^4.1.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  logger: ^2.5.0
  mockito: ^5.4.4
  package_info_plus: ^8.1.2
  # reown_appkit: ^1.0.2
  reown_appkit:
    path: ../reown_appkit/

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
