name: reown_sign
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.0.2
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_sign

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  convert: ^3.0.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  http: ^1.2.0
  pointycastle: ^3.9.1
  reown_core: ^1.0.2
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.7
  build_version: ^2.1.1
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.0
  logger: ^2.2.0
  mockito: ^5.4.3
  package_info_plus: ^8.0.2

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
