name: reown_sign
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.0.4
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_sign

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  convert: ^3.1.2
  event: ^3.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  pointycastle: ^3.9.1
  # reown_core: ^1.0.4
  reown_core:
    path: ../reown_core/
  web3dart: ^2.7.3

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  dependency_validator: ^4.1.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  logger: ^2.5.0
  mockito: ^5.4.4
  package_info_plus: ^8.1.1

platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:
