name: reown_appkit
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.2.0
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_appkit
documentation: https://docs.reown.com/appkit/flutter/core/installation

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  appcheck: ^1.5.2
  cached_network_image: ^3.4.1
  coinbase_wallet_sdk: ^1.0.10
  collection: ^1.18.0
  convert: ^3.1.2
  cupertino_icons: ^1.0.8
  custom_sliding_segmented_control: ^1.8.4
  event: ^3.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.15
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  http: ^1.2.2
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8
  qr_flutter_wc: ^0.0.3
  # reown_core: ^1.0.4
  reown_core:
    path: ../reown_core/
  # reown_sign: ^1.0.4
  reown_sign:
    path: ../reown_sign/
  shimmer: ^3.0.0
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.1.0
  webview_flutter_wkwebview: ^3.16.2

dev_dependencies:
  build_runner: ^2.4.13
  build_version: ^2.1.1
  dependency_validator: ^4.1.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^5.0.0
  logger: ^2.5.0
  mockito: ^5.4.4
  package_info_plus: ^8.1.1
  # reown_walletkit: ^1.0.3
  reown_walletkit:
    path: ../reown_walletkit/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - lib/modal/assets/
    - lib/modal/assets/dark/
    - lib/modal/assets/light/
    - lib/modal/assets/icons/
    - lib/modal/assets/icons/regular/
    - lib/modal/assets/help/
    - lib/modal/assets/png/
    - lib/modal/assets/png/2.0x/
    - lib/modal/assets/png/3.0x/

# TODO check this
platforms:
  android:
  ios:
  # web:
  # macos:
  # linux:
  # windows:
