name: reown_appkit
description: "Reown is the onchain UX platform that provides toolkits built on top of the WalletConnect Network"
version: 1.2.0-beta02
homepage: https://github.com/reown-com/reown_flutter
repository: https://github.com/reown-com/reown_flutter/tree/master/packages/reown_appkit
documentation: https://docs.reown.com/appkit/flutter/core/installation

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  appcheck: ^1.5.1
  cached_network_image: ^3.4.0
  coinbase_wallet_sdk: ^1.0.10
  collection: ^1.18.0
  convert: ^3.1.1
  cupertino_icons: ^1.0.2
  custom_sliding_segmented_control: ^1.8.1
  event: ^2.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  get_it: ^8.0.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8
  qr_flutter_wc: ^0.0.3
  reown_core: ^1.0.4
  # reown_core:
  #   path: ../reown_core/
  reown_sign: ^1.0.4
  # reown_sign:
  #   path: ../reown_sign/
  shimmer: ^3.0.0
  uuid: ^4.5.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  build_runner: ^2.4.7
  build_version: ^2.1.1
  dependency_validator: ^3.2.2
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.0
  lints: ^4.0.0
  logger: ^2.2.0
  mockito: ^5.4.3
  package_info_plus: ^8.0.2
  reown_walletkit: ^1.0.3
  # reown_walletkit:
  #   path: ../reown_walletkit/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - lib/modal/assets/
    - lib/modal/assets/dark/
    - lib/modal/assets/light/
    - lib/modal/assets/icons/
    - lib/modal/assets/icons/regular/
    - lib/modal/assets/help/
    - lib/modal/assets/png/
    - lib/modal/assets/png/2.0x/
    - lib/modal/assets/png/3.0x/

# TODO check this
platforms:
  android:
  ios:
  # web:
  # macos:
  # linux:
  # windows:
