name: reown_appkit_modal_example
description: "Reown's AppKit modal example"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.1
  reown_appkit:
    path: ../..
  shared_preferences: ^2.3.4
  toastification: ^2.3.0

# dependency_overrides:
#   coinbase_wallet_sdk:
#     git:
#       url: https://github.com/WalletConnect/wallet-mobile-sdk.git
#       ref: "2.0"
#       path: flutter

dev_dependencies:
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/abis/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
