name: reown_walletkit_wallet
description: An example wallet for Reown's WalletKit built with Flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3"
  flutter: ">=3.16.6"

dependencies:
  bech32: ^0.2.2
  bitcoin_base: ^6.0.0
  blockchain_utils: ^5.4.0
  bs58: ^1.0.2
  cached_network_image: ^3.4.1
  convert: ^3.1.2
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  eth_sig_util: ^0.0.9
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  http: ^1.2.2
  json_annotation: ^4.9.0
  kadena_dart_sdk: ^2.3.2
  on_chain: ^7.1.0
  package_info_plus: ^8.1.2
  pointycastle: '>=3.9.1 <5.0.0'
  polkadart: '>=0.4.7 <0.8.0'
  polkadart_keyring: '>=0.4.4 <0.8.0'
  qr_bar_code_scanner_dialog:
    path: packages/qr-bar-code-scanner-dialog
  reown_walletkit:
    path: ../
  reown_yttrium_utils:
    path: ../../reown_yttrium_utils/
  sentry_flutter: ^9.7.0
  shared_preferences: ^2.3.4
  solana: ^0.31.2+1
  solana_web3: ^0.1.3
  toastification: ^2.3.0

dependency_overrides:
  # because of solana
  freezed_annotation: ^3.1.0
  pinenacl: ^0.6.0
  pointycastle: '>=3.9.1 <5.0.0'
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  config:
    enable-lldb-debugging: false

  assets:
    - assets/
